vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /images/user
            upload_destination: '%kernel.project_dir%/public/images/user'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
